"""empty message

Revision ID: 05ac944e030f
Revises: ef8d0f4cfa4c
Create Date: 2019-11-18 23:58:12.886040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ac944e030f'
down_revision = 'ef8d0f4cfa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=2000), nullable=False),
    sa.Column('country_label', sa.String(length=100), nullable=True),
    sa.Column('country_value', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
