"""empty message

Revision ID: 2fc6cee29bf6
Revises: adedb82e9541
Create Date: 2019-11-18 23:21:42.517896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc6cee29bf6'
down_revision = 'adedb82e9541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=2000), nullable=False),
    sa.Column('country_label', sa.String(length=500), nullable=True),
    sa.Column('country_value', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stamp')
    # ### end Alembic commands ###
