"""empty message

Revision ID: ef8d0f4cfa4c
Revises: 2fc6cee29bf6
Create Date: 2019-11-18 23:38:10.698018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8d0f4cfa4c'
down_revision = '2fc6cee29bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('country_label', sa.String(length=100), nullable=True),
    sa.Column('country_value', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
